package packer

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// TopComments is the default string added before the generated code to notify that it is generated code.
//
// %s is optional and is substituted with the base command line that was used to produce the code.
const TopComments = "// Code generated by `%s`. DO NOT EDIT.\n"

// Config is used to define some parameters used when generating code.
type Config struct {
	TopComments string // header clause (default=TopComments)
	PkgName     string // package name used for the generated file (default="")
}

func (c *Config) init() {
	if c.TopComments == "" {
		c.TopComments = TopComments
	}
	if strings.Contains(c.TopComments, "%s") {
		cmd := []string{filepath.Base(os.Args[0])}
		cmd = append(cmd, os.Args[1:]...)
		c.TopComments = fmt.Sprintf(c.TopComments, strings.Join(cmd, " "))
	}
}
